### ISSUE TITLE
Possible to remove/guard shopt -s expand_aliases behind if condition to run in dash?

### ISSUE THREAD

**Issue by hamishmb** [michaelgchu/Cygwin_Specific_Repo#6]
Hi there,

I was wondering if removing or guarding the:

`shopt -s expand_aliases`

Statement in bundle_cygwin_exe.bash would have any adverse effects. This would allow it to run under dash or other shells. Dash is a lot lighter than bash under Cygwin which means repeated calls to this script can be quicker - the fork performance is so slow that this makes a significant difference when bundling my program.

I'm happy to submit another pull request for this, but am not sure of the potential impact as I am not particularly familiar with these features of bash. The script seems to run okay without it, but figure I should check first.

Hamish

**Comment by michaelgchu** [comment]
Hi Hamish

That can definitely come out. It's a feature to allow the use of aliases
within a script, which I enabled specifically for the debug messages that
are printed via this defined alias:
alias  debugsay='test $DEV_MODE = "yes" && echo '

I used to do this all the time in my scripts, before I realized it was much
simpler to just run the script with  -x  in order to see everything that's
happening.

To get rid of it means removing all those "debugsay" commands.  I'm fine
with that, and can do it myself - but likely won't get around to it until
at least the weekend.  If you can't wait that long, feel free to make the
pull request and I'll be quick to approve it.

Michael

**Comment by hamishmb** [comment]
Hi Michael,

Good to know. I'm not in a rush - that's fine. Seeing as you're more familiar with how it works I'm happy for you to do that :+1: 

Thank you :)

**Comment by michaelgchu** [comment]
Ok, change is in. Hopefully it works fine in dash now

**Comment by hamishmb** [comment]
All good, thanks :)
